import 'package:flutter/material.dart';

class LanguageInfo {
  final String code;
  final String name;
  final String nativeName;
  final String ttsLocale;
  final String flag;

  const LanguageInfo({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.ttsLocale,
    required this.flag,
  });
}

class LocalizationService extends ChangeNotifier {
  static const List<LanguageInfo> supportedLanguages = [
    LanguageInfo(code: 'en', name: 'English', nativeName: 'English', ttsLocale: 'en-US', flag: '🇬🇧'),
    LanguageInfo(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', ttsLocale: 'ta-IN', flag: '🇮🇳'),
    LanguageInfo(code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', ttsLocale: 'hi-IN', flag: '🇮🇳'),
    LanguageInfo(code: 'te', name: 'Telugu', nativeName: 'తెలుగు', ttsLocale: 'te-IN', flag: '🇮🇳'),
    LanguageInfo(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', ttsLocale: 'kn-IN', flag: '🇮🇳'),
    LanguageInfo(code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', ttsLocale: 'ml-IN', flag: '🇮🇳'),
    LanguageInfo(code: 'zh', name: 'Chinese', nativeName: '中文', ttsLocale: 'zh-CN', flag: '🇨🇳'),
  ];

  String _currentLocale = 'en';

  String get currentLocale => _currentLocale;

  LanguageInfo get currentLanguageInfo =>
      supportedLanguages.firstWhere((l) => l.code == _currentLocale,
          orElse: () => supportedLanguages[0]);

  void setLocale(String langCode) {
    if (_currentLocale != langCode) {
      _currentLocale = langCode;
      notifyListeners();
    }
  }

  // Dictionary of localized strings
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Smart Agri',
      'app_tagline': 'Modern Intelligence for Prosperous Farming',
      'greeting': 'Welcome back, Farmer',
      'weather_risk_alerts': 'Live Weather & Risk Alerts',
      'quick_actions': 'Smart Farming Hub',
      'ai_chat_title': 'Agri AI Doctor',
      'ai_chat_desc': '24/7 Soil, Pest & Organic Guidance',
      'disease_scan_title': 'Leaf Disease AI',
      'disease_scan_desc': 'Instant Leaf Scanner & Cure',
      'crop_advisor_title': 'Crop Advisor',
      'crop_advisor_desc': 'Smart Soil & Season Recommendations',
      'market_rates_title': 'Live Market Rates',
      'market_rates_desc': 'Real-time e-NAM / Mandi Prices',
      'voice_assistant': 'Voice Assistant',
      'tap_to_speak': 'Tap mic to speak...',
      'listening': 'Listening to your question...',
      'action_required': 'Action Required',
      'best_crops_heading': 'Top Recommended Crops for You',
      'view_all': 'View All',
      'profit_estimate': 'Est. Profit',
      'duration': 'Duration',
      'organic_remedy': 'Organic Remedy',
      'chemical_remedy': 'Chemical Treatment',
      'preventive_steps': 'Preventive Steps',
      'select_soil': 'Select Soil Type',
      'select_water': 'Select Water Source',
      'change_language': 'Change Language',
      'mandi_overview': 'Mandi Price Index',
      'price_trend': '24h Trend',
      'today': 'Today',
      'level_critical': 'CRITICAL',
      'level_warning': 'WARNING',
      'level_advisory': 'ADVISORY',
      'level_safe': 'SAFE',
      'alert_heavy_rain_title': '⚠️ Heavy Rain & Inundation Warning',
      'alert_heavy_rain_msg': 'Substantial rainfall expected in the next 24-48 hours. Soil runoff risk is high.',
      'alert_heavy_rain_action': 'Halt fertilizer broadcasting immediately to prevent nutrient leaching. Postpone sprays and open drainage channels.',
      'alert_fungal_title': '🍄 Fungal Blast & Blight Risk High',
      'alert_fungal_msg': 'High ambient humidity and warm weather create optimal breeding grounds for leaf spot, blast, and powdery mildew.',
      'alert_fungal_action': 'Inspect leaf undersides. Prepare bio-fungicide (Trichoderma or Pseudomonas @ 5g/L) for post-rain application.',
      'alert_wind_title': '💨 High Wind Velocity Alert',
      'alert_wind_msg': 'Strong wind gusts may cause lodging in tall standing crops.',
      'alert_wind_action': 'Provide earthing-up and bamboo staking support for banana, papaya, sugarcane, and tomato trellises.',
      'alert_heat_title': '☀️ High Heat & Evapotranspiration',
      'alert_heat_msg': 'High daytime temperatures lead to rapid soil moisture depletion.',
      'alert_heat_action': 'Apply straw mulching around root zones and run drip irrigation early morning or post sunset.',
      'alert_optimal_title': '✅ Optimal Farming Window Ahead',
      'alert_optimal_msg': 'Favorable soil temperature and moderate humidity for field operations.',
      'alert_optimal_action': 'Good time for intercultural weeding, soil aeration, and compost application.',
    },
    'ta': {
      'app_name': 'ஸ்மார்ட் அக்ரி',
      'app_tagline': 'விவசாயிகளின் நவீன டிஜிட்டல் வழிகாட்டி',
      'greeting': 'வணக்கம், விவசாய பெருமக்களே!',
      'weather_risk_alerts': 'நேரலை வானிலை & பயிர் எச்சரிக்கை',
      'quick_actions': 'ஸ்மார்ட் விவசாய மையம்',
      'ai_chat_title': 'விவசாய AI ஆலோசகர்',
      'ai_chat_desc': 'மண், உரம் மற்றும் பூச்சி மேலாண்மை',
      'disease_scan_title': 'இலை நோய் கண்டறிதல்',
      'disease_scan_desc': 'புகைப்படம் எடுத்து உடனடி தீர்வு பெறுக',
      'crop_advisor_title': 'பயிர் பரிந்துரை',
      'crop_advisor_desc': 'மண் & பருவத்திற்கு ஏற்ற அதிக லாப பயிர்கள்',
      'market_rates_title': 'சந்தை விலை நிலவரம்',
      'market_rates_desc': 'உழவர் சந்தை & நேரடி மண்டி விலைகள்',
      'voice_assistant': 'குரல் வழி உதவி',
      'tap_to_speak': 'பேச மைக்கை அழுத்தவும்...',
      'listening': 'உங்கள் கேள்வியை கேட்கிறது...',
      'action_required': 'செய்ய வேண்டியவை',
      'best_crops_heading': 'உங்களுக்கான சிறந்த பயிர்கள்',
      'view_all': 'அனைத்தும் பார்க்க',
      'profit_estimate': 'மதிப்பிடப்பட்ட லாபம்',
      'duration': 'பயிர் காலம்',
      'organic_remedy': 'இயற்கை தீர்வு (பஞ்சகாவ்யா/வேம்பு)',
      'chemical_remedy': 'மருந்து தெளிப்பு அளவு',
      'preventive_steps': 'முன்னெச்சரிக்கை',
      'select_soil': 'மண் வகையை தேர்ந்தெடுக்கவும்',
      'select_water': 'நீர் பாசன வசதி',
      'change_language': 'மொழியை மாற்றவும்',
      'mandi_overview': 'மண்டி சந்தை நிலவரம்',
      'price_trend': '24 மணி நேர விலை மாற்றம்',
      'today': 'இன்று',
      'level_critical': 'அபாயம்',
      'level_warning': 'எச்சரிக்கை',
      'level_advisory': 'அறிவுரை',
      'level_safe': 'பாதுகாப்பானது',
      'alert_heavy_rain_title': '⚠️ கனமழை & வெள்ள அபாய எச்சரிக்கை',
      'alert_heavy_rain_msg': 'அடுத்த 24-48 மணி நேரத்தில் அதிக மழைப்பொழிவு எதிர்பார்க்கப்படுகிறது. மேல்மண் அரிப்பு அபாயம் அதிகம்.',
      'alert_heavy_rain_action': 'உரங்கள் இடுவதை உடனடியாக நிறுத்தவும். மருந்து தெளிப்பதை ஒத்திவைத்து, வடிகால் வாய்க்கால்களை திறந்து விடவும்.',
      'alert_fungal_title': '🍄 பூஞ்சை & இலைக்கருகல் நோய் அபாயம்',
      'alert_fungal_msg': 'அதிக ஈரப்பதம் மற்றும் வெதுவெதுப்பான தட்பவெப்பநிலை காரணமாக இலைப்புள்ளி மற்றும் குலைநோய் வேகமாக பரவ வாய்ப்புள்ளது.',
      'alert_fungal_action': 'இலையின் அடிப்பகுதியை பரிசோதிக்கவும். மழை நின்றவுடன் டிரைக்கோடெர்மா விரிடி (5 கிராம்/லிட்டர்) தெளிக்கவும்.',
      'alert_wind_title': '💨 பலத்த காற்று வீசும் எச்சரிக்கை',
      'alert_wind_msg': 'பலத்த காற்று வீசுவதால் உயரமான பயிர்கள் சாயும் அபாயம் உள்ளது.',
      'alert_wind_action': 'வாழை, பப்பாளி, கரும்பு மற்றும் தக்காளி பயிர்களுக்கு முட்டுக்கொடுத்து பாதுகாக்கவும்.',
      'alert_heat_title': '☀️ கடும் வெப்பம் & நீர் இழப்பு எச்சரிக்கை',
      'alert_heat_msg': 'அதிக பகல் வெப்பநிலையால் மண்ணின் ஈரப்பதம் விரைவாக குறைகிறது.',
      'alert_heat_action': 'வேர் பகுதியில் வைக்கோல் மூடாக்கு அமைக்கவும். அதிகாலை அல்லது மாலையில் சொட்டுநீர் பாசனம் செய்யவும்.',
      'alert_optimal_title': '✅ சாதகமான விவசாய சூழல்',
      'alert_optimal_msg': 'வயல் பணிகளுக்கு ஏற்ற சாதகமான மண் வெப்பநிலை மற்றும் மிதமான ஈரப்பதம் நிலவுகிறது.',
      'alert_optimal_action': 'களை எடுத்தல், மண் கிளறுதல் மற்றும் இயற்கை உரம் இடுவதற்கு இது சிறந்த நேரம்.',
    },
    'hi': {
      'app_name': 'स्मार्ट एग्री',
      'app_tagline': 'समृद्ध खेती के लिए आधुनिक एआई साथी',
      'greeting': 'नमस्ते किसान भाई!',
      'weather_risk_alerts': 'लाइव मौसम और जोखिम अलर्ट',
      'quick_actions': 'स्मार्ट कृषि हब',
      'ai_chat_title': 'कृषि एआई डॉक्टर',
      'ai_chat_desc': 'मिट्टी, खाद और कीट निवारण सलाह',
      'disease_scan_title': 'पत्ती रोग स्कैनर',
      'disease_scan_desc': 'फोटो खींचें और तुरंत सटीक इलाज पाएं',
      'crop_advisor_title': 'फसल सलाहकार',
      'crop_advisor_desc': 'मौसम और मिट्टी अनुसार सबसे लाभदायक फसल',
      'market_rates_title': 'मंडी लाइव भाव',
      'market_rates_desc': 'ई-नाम एवं नजदीकी मंडी के ताज़ा रेट',
      'voice_assistant': 'आवाज़ सहायक',
      'tap_to_speak': 'बोलने के लिए माइक दबाएं...',
      'listening': 'सुन रहा हूँ...',
      'action_required': 'आवश्यक कदम',
      'best_crops_heading': 'आपके लिए सर्वोत्तम अनुशंसित फसलें',
      'view_all': 'सभी देखें',
      'profit_estimate': 'अनुमानित मुनाफा',
      'duration': 'अवधि',
      'organic_remedy': 'जैविक उपचार',
      'chemical_remedy': 'रासायनिक उपचार व मात्रा',
      'preventive_steps': 'रोकथाम के उपाय',
      'select_soil': 'मिट्टी का प्रकार चुनें',
      'select_water': 'सिंचाई स्रोत',
      'change_language': 'भाषा बदलें',
      'mandi_overview': 'मंडी भाव सूचकांक',
      'price_trend': '24 घंटे का रुझान',
      'today': 'आज',
      'level_critical': 'गंभीर',
      'level_warning': 'चेतावनी',
      'level_advisory': 'सलाह',
      'level_safe': 'सुरक्षित',
      'alert_heavy_rain_title': '⚠️ भारी बारिश और जलभराव की चेतावनी',
      'alert_heavy_rain_msg': 'अगले 24-48 घंटों में भारी बारिश की संभावना है। मिट्टी के कटाव व पोषक तत्व बहने का खतरा है।',
      'alert_heavy_rain_action': 'यूरिया/उर्वरक का छिड़काव तुरंत रोकें। कीटनाशक छिड़काव स्थगित करें और खेत की जलनिकासी नालियां खोलें।',
      'alert_fungal_title': '🍄 फंगल ब्लास्ट और झुलसा रोग का खतरा',
      'alert_fungal_msg': 'उच्च आर्द्रता और गर्म मौसम के कारण पत्ती धब्बा व झुलसा रोग तेजी से फैल सकता है।',
      'alert_fungal_action': 'पत्तियों के निचले हिस्से की जांच करें। बारिश के बाद ट्राइकोडर्मा (5 ग्राम/लीटर) का छिड़काव करें।',
      'alert_wind_title': '💨 तेज हवा और आंधी का अलर्ट',
      'alert_wind_msg': 'तेज हवाओं से खड़ी और लंबी फसलों के गिरने का खतरा हो सकता है।',
      'alert_wind_action': 'केला, पपीता, गन्ना और टमाटर की फसलों को सहारा (स्टेकिंग) दें।',
      'alert_heat_title': '☀️ अत्यधिक तापमान और नमी ह्रास',
      'alert_heat_msg': 'दिन के उच्च तापमान से मिट्टी की नमी तेजी से कम हो रही है।',
      'alert_heat_action': 'जड़ों के पास पुआल की मल्चिंग करें। सुबह या शाम को ड्रिप सिंचाई करें।',
      'alert_optimal_title': '✅ खेती के अनुकूल मौसम',
      'alert_optimal_msg': 'खेत के कार्यों के लिए अनुकूल तापमान और मध्यम आर्द्रता है।',
      'alert_optimal_action': 'निराई-गुड़ाई, मिट्टी की जुताई और जैविक खाद डालने का उत्तम समय।',
    },
    'te': {
      'app_name': 'స్మార్ట్ అగ్రి',
      'app_tagline': 'రైతు సోదరులకు ఆధునిక వ్యవసాయ సలహాదారు',
      'greeting': 'నమస్కారం రైతు మిత్రమా!',
      'weather_risk_alerts': 'వాతావరణం & హెచ్చరికలు',
      'quick_actions': 'వ్యవసాయ హబ్',
      'ai_chat_title': 'వ్యవసాయ AI సహాయకుడు',
      'ai_chat_desc': 'నేల, ఎరువులు మరియు తెగుళ్ళ నివారణ',
      'disease_scan_title': 'ఆకు తెగులు స్కానర్',
      'disease_scan_desc': 'ఫోటో తీసి తక్షణ నివారణ పొందండి',
      'crop_advisor_title': 'పంట సిఫార్సు',
      'crop_advisor_desc': 'నేల రకం మరియు సీజన్‌కు సరిపోయే పంటలు',
      'market_rates_title': 'మార్కెట్ ధరలు',
      'market_rates_desc': 'ఈ-నామ్ మరియు మార్కెట్ యార్డ్ లైవ్ రేట్లు',
      'voice_assistant': 'వాయిస్ అసిస్టెంట్',
      'tap_to_speak': 'మాట్లాడటానికి మైక్ నొక్కండి...',
      'listening': 'వింటున్నాను...',
      'action_required': 'చేయవలసిన పనులు',
      'best_crops_heading': 'సిఫార్సు చేయబడిన ఉత్తమ పంటలు',
      'view_all': 'అన్నీ చూడండి',
      'profit_estimate': 'అంచనా లాభం',
      'duration': 'కాలవ్యవధి',
      'organic_remedy': 'సేంద్రీయ నివారణ',
      'chemical_remedy': 'రసాయన మందుల మోతాదు',
      'preventive_steps': 'నివారణ చర్యలు',
      'select_soil': 'నేల రకాన్ని ఎంచుకోండి',
      'select_water': 'నీటి వనరు',
      'change_language': 'భాష మార్చుకోండి',
      'mandi_overview': 'మార్కెట్ సారాంశం',
      'price_trend': '24 గంటల ట్రెండ్',
      'today': 'ఈ రోజు',
      'level_critical': 'తీవ్రం',
      'level_warning': 'హెచ్చరిక',
      'level_advisory': 'సలహా',
      'level_safe': 'సురక్షితం',
      'alert_heavy_rain_title': '⚠️ భారీ వర్షం & వరద హెచ్చరిక',
      'alert_heavy_rain_msg': 'రాబోయే 24-48 గంటల్లో భారీ వర్షపాతం నమోదయ్యే అవకాశం ఉంది.',
      'alert_heavy_rain_action': 'ఎరువులు వేయడం వెంటనే ఆపండి. మందుల పిచికారీ వాయిదా వేసి, మురుగు కాలువలు తెరవండి.',
      'alert_fungal_title': '🍄 శిలీంధ్ర తెగులు & ఆకుమచ్చ ముప్పు',
      'alert_fungal_msg': 'అధిక తేమ వల్ల ఆకుమచ్చ, అగ్గితెగులు వేగంగా వ్యాపించే ప్రమాదం ఉంది.',
      'alert_fungal_action': 'ఆకుల అడుగుభాగాన్ని గమనించండి. వర్షం తగ్గాక ట్రైకోడెర్మా (5 గ్రా/లీ) పిచికారీ చేయండి.',
      'alert_wind_title': '💨 ఈదురు గాలుల హెచ్చరిక',
      'alert_wind_msg': 'ఈదురు గాలుల వల్ల అరటి, బొప్పాయి, చెరకు పంటలు నేలవాలే ప్రమాదం ఉంది.',
      'alert_wind_action': 'ఎత్తుగా ఉండే పంటలకు వెదురు కర్రలతో ఆధారం ఇవ్వండి.',
      'alert_heat_title': '☀️ తీవ్ర ఉష్ణోగ్రత & తేమ కొరత',
      'alert_heat_msg': 'ఎండ వేడిమి వల్ల నేలలో తేమ వేగంగా ఆవిరవుతోంది.',
      'alert_heat_action': 'వేర్ల వద్ద గడ్డితో మల్చింగ్ చేయండి. ఉదయం లేదా సాయంత్రం డ్రిప్ ద్వారా నీరందించండి.',
      'alert_optimal_title': '✅ సాగుకు అనుకూలమైన వాతావరణం',
      'alert_optimal_msg': 'వ్యవసాయ పనులకు అనుకూలమైన ఉష్ణోగ్రత మరియు తేమ ఉన్నాయి.',
      'alert_optimal_action': 'కలుపు తీయడం, అంతరకృషి మరియు సేంద్రీయ ఎరువులు వేయడానికి ఇది సరైన సమయం.',
    },
    'kn': {
      'app_name': 'ಸ್ಮಾರ್ಟ್ ಅಗ್ರಿ',
      'app_tagline': 'ರೈತ ಮಿತ್ರರಿಗೆ ಆಧುನಿಕ ತಂತ್ರಜ್ಞಾನ',
      'greeting': 'ನಮಸ್ಕಾರ ರೈತ ಬಾಂಧವರೇ!',
      'weather_risk_alerts': 'ಹವಾಮಾನ ಮತ್ತು ಮುನ್ಸೂಚನೆ',
      'quick_actions': 'ಕೃಷಿ ಕೇಂದ್ರ',
      'ai_chat_title': 'ಕೃಷಿ AI ವೈದ್ಯ',
      'ai_chat_desc': 'ಮಣ್ಣು, ಗೊಬ್ಬರ ಮತ್ತು ಕೀಟ ನಿಯಂತ್ರಣ',
      'disease_scan_title': 'ಎಲೆ ರೋಗ ಪತ್ತೆ',
      'disease_scan_desc': 'ಫೋಟೋ ತೆಗೆದು ರೋಗ ನಿಯಂತ್ರಣ ತಿಳಿಯಿರಿ',
      'crop_advisor_title': 'ಬೆಳೆ ಶಿಫಾರಸು',
      'crop_advisor_desc': 'ಮಣ್ಣಿಗೆ ತಕ್ಕಂತೆ ಅಧಿಕ ಲಾಭದಾಯಕ ಬೆಳೆಗಳು',
      'market_rates_title': 'ಮಾರುಕಟ್ಟೆ ದರಗಳು',
      'market_rates_desc': 'ಇ-ನ್ಯಾಮ್ ಮತ್ತು ಎಪಿಎಂಸಿ ಮಾರುಕಟ್ಟೆ ದರ',
      'voice_assistant': 'ಧ್ವನಿ ಸಹಾಯಕ',
      'tap_to_speak': 'ಮಾತನಾಡಲು ಮೈಕ್ ಒತ್ತಿರಿ...',
      'listening': 'ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇನೆ...',
      'action_required': 'ತೆಗೆದುಕೊಳ್ಳಬೇಕಾದ ಕ್ರಮ',
      'best_crops_heading': 'ಉತ್ತಮ ಶಿಫಾರಸು ಮಾಡಲಾದ ಬೆಳೆಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'profit_estimate': 'ಅಂದಾಜು ಲಾಭ',
      'duration': 'ಅವಧಿ',
      'organic_remedy': 'ಸಾವಯವ ಪರಿಹಾರ',
      'chemical_remedy': 'ರಾಸಾಯನಿಕ ಔಷಧಿ ಪ್ರಮಾಣ',
      'preventive_steps': 'ಮುನ್ನೆಚ್ಚರಿಕೆ ಕ್ರಮಗಳು',
      'select_soil': 'ಮಣ್ಣಿನ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ',
      'select_water': 'ನೀರಿನ ಲಭ್ಯತೆ',
      'change_language': 'ಭಾಷೆ ಬದಲಿಸಿ',
      'mandi_overview': 'ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ',
      'price_trend': '24 ಗಂಟೆ ಬದಲಾವಣೆ',
      'today': 'ಇಂದು',
      'level_critical': 'ಗಂಭೀರ',
      'level_warning': 'ಎಚ್ಚರಿಕೆ',
      'level_advisory': 'ಸಲಹೆ',
      'level_safe': 'ಸುರಕ್ಷಿತ',
      'alert_heavy_rain_title': '⚠️ ಭಾರಿ ಮಳೆ ಮತ್ತು ಪ್ರವಾಹದ ಮುನ್ಸೂಚನೆ',
      'alert_heavy_rain_msg': 'ಮುಂದಿನ 24-48 ಗಂಟೆಗಳಲ್ಲಿ ಭಾರಿ ಮಳೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ. ಮಣ್ಣಿನ ಸವೆತದ ಅಪಾಯವಿದೆ.',
      'alert_heavy_rain_action': 'ರಸಗೊಬ್ಬರ ಸಿಂಪಡಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ. ಕೀಟನಾಶಕ ಸಿಂಪಡಣೆ ಮುಂದೂಡಿ, ಕಾಲುವೆಗಳನ್ನು ತೆರೆಯಿರಿ.',
      'alert_fungal_title': '🍄 ಶಿಲೀಂಧ್ರ ರೋಗ ಮತ್ತು ಎಲೆಚುಕ್ಕೆ ಅಪಾಯ',
      'alert_fungal_msg': 'ಹೆಚ್ಚಿನ ತೇವಾಂಶದಿಂದ ಎಲೆಚುಕ್ಕೆ ಹಾಗೂ ಬೆಂಕಿ ರೋಗ ಹರಡುವ ಸಾಧ್ಯತೆ ಹೆಚ್ಚಿದೆ.',
      'alert_fungal_action': 'ಎಲೆಯ ಕೆಳಭಾಗ ತಪಾಸಣೆ ಮಾಡಿ. ಮಳೆ ನಿಂತ ನಂತರ ಟ್ರೈಕೋಡರ್ಮ ಸಿಂಪಡಿಸಿ.',
      'alert_wind_title': '💨 ಬಿರುಗಾಳಿ ಬೀಸುವ ಎಚ್ಚರಿಕೆ',
      'alert_wind_msg': 'ವೇಗದ ಗಾಳಿಯಿಂದ ಬೆಳೆಗಳು ನೆಲಕ್ಕುರುಳುವ ಅಪಾಯವಿದೆ.',
      'alert_wind_action': 'ಬಾಳೆ, ಕಬ್ಬು, ಪಪ್ಪಾಯಿ ಮತ್ತು ಟೊಮ್ಯಾಟೊ ಗಿಡಗಳಿಗೆ ಬಿದಿರಿನ ಆಸರೆ ನೀಡಿ.',
      'alert_heat_title': '☀️ ತೀವ್ರ ಶಾಖ ಮತ್ತು ನೀರಿನ ಕೊರತೆ',
      'alert_heat_msg': 'ಹೆಚ್ಚಿನ ತಾಪಮಾನದಿಂದ ಮಣ್ಣಿನ ತೇವಾಂಶ ಶೀಘ್ರವಾಗಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ.',
      'alert_heat_action': 'ಬುಡಕ್ಕೆ ಕಸದ ಹೊದಿಕೆ ಮಾಡಿ. ಮುಂಜಾನೆ ಅಥವಾ ಸಂಜೆ ಹನಿ ನೀರಾವರಿ ಒದಗಿಸಿ.',
      'alert_optimal_title': '✅ ಕೃಷಿ ಕಾರ್ಯಕ್ಕೆ ಸೂಕ್ತ ಹವಾಮಾನ',
      'alert_optimal_msg': 'ಹೊಲದ ಕೆಲಸಗಳಿಗೆ ಅನುಕೂಲಕರವಾದ ವಾತಾವರಣವಿದೆ.',
      'alert_optimal_action': 'ಕಳೆ ಕೀಳಲು, ಮಣ್ಣು ಹದಗೊಳಿಸಲು ಮತ್ತು ಗೊಬ್ಬರ ಹಾಕಲು ಇದು ಸಕಾಲ.',
    },
    'ml': {
      'app_name': 'സ്മാർട്ട് അഗ്രി',
      'app_tagline': 'കർഷകർക്കായുള്ള ആധുനിക എഐ സഹായി',
      'greeting': 'സ്വാഗതം കർഷക സുഹൃത്തേ!',
      'weather_risk_alerts': 'കാലാവസ്ഥ മുന്നറിയിപ്പുകൾ',
      'quick_actions': 'കൃഷി കേന്ദ്രം',
      'ai_chat_title': 'കൃഷി എഐ ഡോക്ടർ',
      'ai_chat_desc': 'മണ്ണും വളവും കീട നിയന്ത്രണവും',
      'disease_scan_title': 'ഇല രോഗ നിർണയം',
      'disease_scan_desc': 'ചിത്രമെടുത്ത് തത്സമയം പരിഹാരം കാണുക',
      'crop_advisor_title': 'വിള നിർദ്ദേശം',
      'crop_advisor_desc': 'മണ്ണിനും കാലത്തിനും അനുയോജ്യമായ വിളകൾ',
      'market_rates_title': 'വിപണി വിലനിലവാരം',
      'market_rates_desc': 'തത്സമയ ചന്ത വില വിവരങ്ങൾ',
      'voice_assistant': 'വോയ്സ് അസിസ്റ്റന്റ്',
      'tap_to_speak': 'സംസാരിക്കാൻ മൈക്ക് അമർത്തുക...',
      'listening': 'കേൾക്കുന്നു...',
      'action_required': 'സ്വീകരിക്കേണ്ട നടപടി',
      'best_crops_heading': 'നിങ്ങൾക്കായുള്ള മികച്ച വിളകൾ',
      'view_all': 'എല്ലാം കാണുക',
      'profit_estimate': 'പ്രതീക്ഷിക്കുന്ന ലാഭം',
      'duration': 'വിളവെടുപ്പ് കാലം',
      'organic_remedy': 'ജൈവ പരിഹാരം',
      'chemical_remedy': 'കീടനാശിനി അളവ്',
      'preventive_steps': 'പ്രതിരോധ നടപടികൾ',
      'select_soil': 'മണ്ണിന്റെ തരം തിരഞ്ഞെടുക്കുക',
      'select_water': 'ജലസേചന സൗകര്യം',
      'change_language': 'ഭാഷ മാറ്റുക',
      'mandi_overview': 'വിപണി സൂചിക',
      'price_trend': '24 മണിക്കൂർ മാറ്റം',
      'today': 'ഇന്ന്',
      'level_critical': 'ഗുരുതരം',
      'level_warning': 'മുന്നറിയിപ്പ്',
      'level_advisory': 'നിർദ്ദേശം',
      'level_safe': 'സുരക്ഷിതം',
      'alert_heavy_rain_title': '⚠️ കനത്ത മഴ & വെള്ളപ്പൊക്ക മുന്നറിയിപ്പ്',
      'alert_heavy_rain_msg': 'അടുത്ത 24-48 മണിക്കൂറിൽ കനത്ത മഴ സാധ്യത. മണ്ണൊലിപ്പ് തടയാൻ ശ്രദ്ധിക്കുക.',
      'alert_heavy_rain_action': 'വളം ഇടുന്നത് ഉടൻ നിർത്തുക. കീടനാശിനി പ്രയോഗം മാറ്റിവെച്ച് ചാലുകൾ വൃത്തിയാക്കുക.',
      'alert_fungal_title': '🍄 കുമിൾ രോഗ സാധ്യത',
      'alert_fungal_msg': 'ഉയർന്ന അന്തരീക്ഷ ഈർപ്പം മൂലം ഇലപ്പുള്ളി, കുമിൾ രോഗങ്ങൾ പടരാൻ സാധ്യതയുണ്ട്.',
      'alert_fungal_action': 'ഇലകളുടെ അടിഭാഗം പരിശോധിക്കുക. മഴ മാറിയ ശേഷം ട്രൈക്കോഡെർമ തളിക്കുക.',
      'alert_wind_title': '💨 ശക്തമായ കാറ്റ് മുന്നറിയിപ്പ്',
      'alert_wind_msg': 'ശക്തമായ കാറ്റിൽ ഉയരമുള്ള വിളകൾ നിലംപൊത്താൻ സാധ്യതയുണ്ട്.',
      'alert_wind_action': 'വാഴ, പപ്പായ, കരിമ്പ് വിളകൾക്ക് താങ്ങ് നൽകുക.',
      'alert_heat_title': '☀️ കടുത്ത ചൂട് & ഈർപ്പക്കുറവ്',
      'alert_heat_msg': 'ഉയർന്ന ചൂട് കാരണം മണ്ണിലെ ഈർപ്പം വേഗത്തിൽ വറ്റുന്നു.',
      'alert_heat_action': 'തടങ്ങളിൽ പുതയിടുക. അതിരാവിലെയോ വൈകുന്നേരമോ നനയ്ക്കുക.',
      'alert_optimal_title': '✅ കൃഷിക്ക് അനുകൂലമായ കാലാവസ്ഥ',
      'alert_optimal_msg': 'കൃഷിപ്പണികൾക്ക് അനുയോജ്യമായ താപനിലയും മിതമായ ഈർപ്പവും.',
      'alert_optimal_action': 'കള പറിക്കാനും മണ്ണ് ഇളക്കാനും ജൈവവളം ചേർക്കാനും അനുയോജ്യമായ സമയം.',
    },
    'zh': {
      'app_name': '智慧农业 (Smart Agri)',
      'app_tagline': '年轻农民的现代AI农业助手',
      'greeting': '欢迎回来，农友！',
      'weather_risk_alerts': '实时气象与农业灾害预警',
      'quick_actions': '智慧农业服务中心',
      'ai_chat_title': '农业AI专家',
      'ai_chat_desc': '24小时土壤、肥料与病虫害咨询',
      'disease_scan_title': '叶片病害AI诊断',
      'disease_scan_desc': '拍照即刻诊断病害与防治配方',
      'crop_advisor_title': '智能作物推荐',
      'crop_advisor_desc': '基于土壤与季节的高收益种植方案',
      'market_rates_title': '农产品实时行情',
      'market_rates_desc': '全国各大批发市场与期货走势',
      'voice_assistant': '语音助手',
      'tap_to_speak': '点击麦克风说话...',
      'listening': '正在聆听您的提问...',
      'action_required': '应对措施',
      'best_crops_heading': '为您推荐的最佳适种作物',
      'view_all': '查看全部',
      'profit_estimate': '预计亩产效益',
      'duration': '生育周期',
      'organic_remedy': '有机绿色防治',
      'chemical_remedy': '精准农药配比',
      'preventive_steps': '预防措施',
      'select_soil': '选择土壤类型',
      'select_water': '灌溉水源条件',
      'change_language': '切换语言',
      'mandi_overview': '市场行情概览',
      'price_trend': '24小时走势',
      'today': '今天',
      'level_critical': '严重预警',
      'level_warning': '警告',
      'level_advisory': '建议',
      'level_safe': '安全',
      'alert_heavy_rain_title': '⚠️ 强降雨及田间积水预警',
      'alert_heavy_rain_msg': '未来24-48小时预计将有强降雨，土壤养分流失与积水风险高。',
      'alert_heavy_rain_action': '立即暂停撒施化肥，推迟打药，清理并疏通田间排灌沟渠。',
      'alert_fungal_title': '🍄 真菌性病害与叶斑病高发预警',
      'alert_fungal_msg': '高湿度环境与温暖气候极易滋生叶斑病、稻瘟病及白粉病。',
      'alert_fungal_action': '仔细检查叶片背面。雨后喷施木霉菌或枯草芽孢杆菌进行生物防治。',
      'alert_wind_title': '💨 大风天气与倒伏预警',
      'alert_wind_msg': '阵风风力较大，高秆及攀爬作物存在倒伏折断风险。',
      'alert_wind_action': '对香蕉、木瓜、甘蔗以及番茄搭架支撑加固，培土护根。',
      'alert_heat_title': '☀️ 高温蒸发与干旱预警',
      'alert_heat_msg': '白天高温将导致土壤水分迅速蒸发，引发作物萎蔫。',
      'alert_heat_action': '根际进行秸秆覆盖保墒，清晨或傍晚进行滴灌补水。',
      'alert_optimal_title': '✅ 农事作业最佳窗口期',
      'alert_optimal_msg': '当前土壤温湿度适宜，无恶劣天气干扰。',
      'alert_optimal_action': '适宜进行田间中耕除草、土壤透气松土及增施有机堆肥。',
    },
  };

  String tr(String key) {
    if (_localizedValues.containsKey(_currentLocale)) {
      if (_localizedValues[_currentLocale]!.containsKey(key)) {
        return _localizedValues[_currentLocale]![key]!;
      }
    }
    return _localizedValues['en']?[key] ?? key;
  }
}
